version: '3.7'

services:
    client:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - 3000:3000
        volumes:
            - "/app/node_modules"
            - ".:/app"
        environment:
            - CHOKIDAR_USEPOLLING=true
